# Generated by Django 2.0.3 on 2019-02-13 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(default='', max_length=40)),
                ('lastname', models.CharField(default='', max_length=40)),
                ('email', models.EmailField(default='', max_length=100)),
                ('password', models.IntegerField(default=0)),
                ('birthday', models.DateTimeField()),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
    ]
