# Generated by Django 2.1.1 on 2019-02-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='password',
            field=models.IntegerField(max_length=30),
        ),
    ]
